Repository cmu-delphi/delphi-epidata, pull requests merged in 2021-06, with the labels that each got.

#570 chore: add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#571 dynamically check if the missing_* columns exist
  src/server/_db.py
  src/server/endpoints/covidcast.py
Labels: enhancement

#572 add a simple coverage endpoint
  integrations/server/test_covidcast_endpoints.py
  src/server/endpoints/covidcast.py
Labels: enhancement

#576 feat: add /covidcast/anomalies endpoint
  src/server/endpoints/covidcast.py
Labels: enhancement

#577 fix: trendseries serialization + require signal in coverage endpoint
  src/server/endpoints/covidcast.py
Labels: bug

#587 ci: enforce origin/dev branch in creating release
  .github/workflows/create-delphi-epidata-release.yml
Labels: chore

#591 docs: fix wrong endpoint url in covid_hosp
  docs/api/covid_hosp.md
Labels: documentation

#590 cleanup docs job
  .github/workflows/deploy-docs.yaml
  deploy.json
Labels: chore

#602 Fix covid hosp as_of to only return latest issue
  integrations/server/test_covid_hosp.py
  src/server/endpoints/covid_hosp_state_timeseries.py
Labels: api change, bug

#598 finish add SQL Query and pass the integrations tests
  integrations/acquisition/covidcast/test_covidcast_meta_caching.py
  integrations/client/test_delphi_epidata.py
  integrations/server/test_covidcast.py
  integrations/server/test_covidcast_endpoints.py
  integrations/server/test_covidcast_meta.py
  integrations/server/test_fluview.py
  integrations/server/test_fluview_meta.py
Labels: chore

#603 feat: remove missing workaround
  src/server/endpoints/covidcast.py
Labels: chore

#605 Main -> dev sync
  .bumpversion.cfg
  src/client/delphi_epidata.R
  src/client/delphi_epidata.js
  src/client/packaging/npm/package.json
  src/client/packaging/pypi/delphi_epidata/__init__.py
  src/client/packaging/pypi/setup.py
  src/server/_config.py
Labels: chore

#600 ci: add release helper
  .github/release-drafter.yml
  .github/workflows/create-release.yml
  .github/workflows/release-helper.yml
  src/client/packaging/npm/.gitignore
  src/client/packaging/npm/LICENSE
  src/client/packaging/npm/README.md
  src/client/packaging/npm/package.json
  src/client/packaging/pypi/.gitignore
Labels: chore

#611 Covidcast logging
  src/acquisition/covidcast/covidcast_meta_cache_updater.py
  src/acquisition/covidcast/csv_importer.py
  src/acquisition/covidcast/csv_to_database.py
  src/acquisition/covidcast/database.py
  src/acquisition/covidcast/file_archiver.py
  src/acquisition/covidcast/fill_is_latest_issue.py
  src/acquisition/covidcast/generate_islatest_fix_sql.py
Labels: acquisition, refactor

#616 fix relative links in docs to absolute links
  docs/api/afhsb.md
  docs/api/cdc.md
  docs/api/covid_hosp.md
  docs/api/covid_hosp_facility.md
  docs/api/covid_hosp_facility_lookup.md
  docs/api/covidcast_meta.md
  docs/api/flusurv.md
  docs/api/fluview.md
  docs/api/fluview_clinical.md
  docs/api/gft.md
  docs/api/ght.md
  docs/api/nidss_dengue.md
  docs/api/nidss_flu.md
  docs/api/nowcast.md
  docs/api/quidel.md
  docs/api/sensors.md
  docs/api/twitter.md
  docs/api/wiki.md
  docs/epidata_development.md
  docs/new_endpoint_tutorial.md
Labels: documentation
