Repository cmu-delphi/delphi-epidata, pull requests merged in 2021-08, with the labels that each got.

#667 feat: move active flag to signal level instead of source level
  src/server/endpoints/covidcast.py
  src/server/endpoints/covidcast_utils/db_signals.csv
  src/server/endpoints/covidcast_utils/db_sources.csv
  src/server/endpoints/covidcast_utils/model.py
Labels: enhancement, api change

#668 fix: timepair for week values not working
  requirements.txt
  src/server/_params.py
  src/server/utils/__init__.py
  src/server/utils/dates.py
  tests/server/utils/test_dates.py
Labels: bug, api change

#669 fix: fix tests for merging #668
  src/server/utils/dates.py
Labels: bug

#680 feat: add missing confirmed_admissions_covid_1d_7dav meta signal
  src/server/endpoints/covidcast_utils/db_signals.csv
Labels: bug

#676 add nchs mortality to meta data and adapt covidcast endpoints
  src/server/_params.py
  src/server/endpoints/covidcast.py
  src/server/endpoints/covidcast_utils/correlation.py
  src/server/endpoints/covidcast_utils/db_signals.csv
  src/server/endpoints/covidcast_utils/db_sources.csv
  src/server/endpoints/covidcast_utils/model.py
  src/server/endpoints/covidcast_utils/trend.py
  src/server/utils/__init__.py
  src/server/utils/dates.py
Labels: enhancement, api change

#687 feat: add basis_shift param to /covidcast/trend
  src/server/endpoints/covidcast.py
Labels: api change

#682 Document schooling deactivation
  docs/symptom-survey/coding.md
Labels: documentation
