Repository cmu-delphi/delphi-epidata, pull requests merged in 2021-07, with the labels that each got.

#623 Update docs to refer to survey as COVID Trends and Impact Survey instead of COVID Symptom Survey
  docs/api/covidcast-signals/fb-survey.md
  docs/symptom-survey/coding.md
  docs/symptom-survey/collaboration-revision.md
  docs/symptom-survey/contingency-tables.md
  docs/symptom-survey/data-access.md
  docs/symptom-survey/index.md
  docs/symptom-survey/modules.md
  docs/symptom-survey/problems.md
  docs/symptom-survey/server-access.md
  docs/symptom-survey/survey-files.md
  docs/symptom-survey/survey-utils.R
  docs/symptom-survey/weights.md
Labels: documentation

#622 fix logger bug for batch issue upload
  src/acquisition/covidcast/csv_importer.py
  tests/acquisition/covidcast/test_csv_importer.py
Labels: acquisition

#564 create meta data covidcast file + use in /meta
  .github/workflows/ci.yaml
  .github/workflows/update_gdocs_data.yml
  integrations/server/test_covidcast_endpoints.py
  requirements.dev.txt
  src/server/endpoints/covidcast.py
  src/server/endpoints/covidcast_utils/__init__.py
  src/server/endpoints/covidcast_utils/db_signals.csv
  src/server/endpoints/covidcast_utils/db_sources.csv
  src/server/endpoints/covidcast_utils/meta.py
  src/server/endpoints/covidcast_utils/model.py
  tasks.py
Labels: api change, enhancement

#632 Mention Cyberduck problem and solution
  docs/symptom-survey/server-access.md
Labels: documentation

#651 fix: lookup of meta data by alias
  src/server/endpoints/covidcast.py
Labels: bug

#661 fix: handle cornercases where source is not transmitted for aliases
  src/server/endpoints/covidcast.py
Labels: bug
